### ISSUE TITLE
Cannot deploy due to "not in GZIP format" error

### ISSUE THREAD

**Issue by poirierlouis** [webjars/webjars#1634]
Hello,

I've tried to add the following package with npm: 

- name: types__escodegen
- version: 0.0.2

Deployment end-up with this following error:

> Failed!
> Not in GZIP format
> If you feel you have reached this failure in error, please file an issue: 
> https://github.com/webjars/webjars/issues

I have to admit I'm not sure if this issue is related to WebJars or if it because of the format of the dependency...
Any idea please ?

**Comment by jamesward** [comment]
I think this was a transient issue downloading the artifact from NPM.  I've deployed this to BinTray but Maven Central syncing seems down at the moment.  So I'll try again later.

**Comment by poirierlouis** [comment]
Hello, have you tried again ?
I still face this issue and I really can't use latest version as my dependencies need v0.0.2.

Thank you in advance.

**Comment by jamesward** [comment]
Hmmm... It seems that the `Not in GZIP format` still exists for `0.0.2` so I'll need to investigate.

**Comment by poirierlouis** [comment]
Thank you for reopening this issue.

I've also tested with `0.0.1`, same error if it can helps you while investigating.

If possible, I'd like to contribute/learn what happen under the hood, maybe you can show me some documentations, links?

**Comment by jamesward** [comment]
So it turns out that the tgz file in NPM isn't really a tar gzip file, it is just a tar.  A fix for this will be deployed shortly.

**Comment by poirierlouis** [comment]
Thank you, deployed with success!
