### ISSUE TITLE
Nginx 405 on deploy

### ISSUE THREAD

**Issue by rob-64** [webjars/webjars#1841]
Can't deploy
![Screenshot_20190323-150417](https://user-images.githubusercontent.com/2374685/54870428-14662500-4d7d-11e9-8d77-44fbe83817b6.jpg)

**Comment by jamesward** [comment]
This seems to be working now.  Perhaps just a transient issue with BinTray.

**Comment by rob-64** [comment]
I am still getting it.. only for vue

**Comment by jamesward** [comment]
Ah. Thanks.  Looks like there is an issue with BinTray.  I've filed a support ticket with them.

**Comment by rob-64** [comment]
Late reply . But thanks for fixing it

**Comment by jamesward** [comment]
I believe we should be good now.

**Comment by ChristianMurphy** [comment]
Issue appears to be back again

**Comment by jamesward** [comment]
This was an upstream issue that is now resolved.

**Comment by ChristianMurphy** [comment]
Thanks @jamesward :bowing_man:

**Comment by cbeach47** [comment]
Hi @jamesward  - the issue that @ChristianMurphy noted is still happening for that webjar artifact / version.

**Comment by jamesward** [comment]
This is working for me.  I wonder if there is actually a problem with the websocket for you.  Maybe a browser extension or proxy server is messing with this?

**Comment by jamesward** [comment]
Sure enough! I've contact BinTray support.

**Comment by jamesward** [comment]
BinTray resolved the issue and I was able to deploy the WebJar but it seems Sonatype is a little wobbly right now so it took a few tries.
