### ISSUE TITLE
invalid jar when deploying bowergithub webjars

### ISSUE THREAD

**Issue by alvarezguille** [webjars/webjars#1862]
Tried doing `jar xf vaadin-usage-statistics-2.0.6.jar` and extracting the contents of the jars and it failed.

Used artifacts from both [maven central](https://repo.maven.apache.org/maven2/org/webjars/bowergithub/vaadin/vaadin-usage-statistics/2.0.6/) and [bintray](https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/vaadin/vaadin-usage-statistics/2.0.6/)

Same command works for 2.0.4 jar. Also tested for other projects.

**Comment by Artur-** [comment]
In the working 2.0.4 version, directories are directories:
```
$ unzip -v vaadin-usage-statistics-2.0.4.jar 
Archive:  vaadin-usage-statistics-2.0.4.jar
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Defl:N        2   0% 06-05-2019 11:20 00000000  META-INF/
       0  Defl:N        2   0% 06-05-2019 11:20 00000000  META-INF/maven/
```

In the broken 2.0.6, directories are files
```
$ unzip -v vaadin-usage-statistics-2.0.5.jar 
Archive:  vaadin-usage-statistics-2.0.5.jar
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Defl:N        2   0% 08-01-2019 13:20 00000000  META-INF
       0  Defl:N        2   0% 08-01-2019 13:20 00000000  maven
       0  Defl:N        2   0% 08-01-2019 13:20 00000000  org.webjars.bowergithub.vaadin
       0  Defl:N        2   0% 08-01-2019 13:20 00000000  vaadin-usage-statistics
```

**Comment by jamesward** [comment]
There was an issue with the creator over the past few days which I fixed yesterday:

**Comment by jamesward** [comment]
Here is a new version to see if it is all fixed:
https://bintray.com/webjars/maven/download_file?file_path=org%2Fwebjars%2Fbowergithub%2Fvaadin%2Fvaadin-usage-statistics%2F2.0.6-1%2Fvaadin-usage-statistics-2.0.6-1.jar

**Comment by alvarezguille** [comment]
I tried `vaadin-usage-statistics-2.0.6-1.jar` and both `jar xf` and `unzip -v` worked as expected

Let us know when these changes are live so we can try and release 2.0.7

Is it possible to check if other bowergithub webjars were released since aa25d8f was deployed?

**Comment by jamesward** [comment]
The changes should be live.  Let me know how it goes.

**Comment by jamesward** [comment]
Oh, and I can check to see what other libraries were released while this was broken but since the artifacts are immutable, it is hard to fix them.  Let's see if this comes up for others.

**Comment by ZheSun88** [comment]
Hi @jamesward , has this issue been fixed?

**Comment by ZheSun88** [comment]
Issue has been fixed, Thanks.

**Comment by alvarezguille** [comment]
It looks like there is some issue still, and webjars resources are still not available in `servletContext.getResouce(`
Comparing working (2.1.4) and not working (2.1.5) versions of webjar for `vaadin-form-layout` it looks like some folders are missing in the list command
![image](https://user-images.githubusercontent.com/9820084/62854511-321a3380-bcf8-11e9-9e71-73140d060003.png)

As mentioned in this comment https://github.com/webjars/webjars/issues/1862#issuecomment-517590886 by @Artur- 
•  working webjar `directories are directories`
•  not working webjar `directories are files`
•  and now not working webjar `directories are missing`

**Comment by alvarezguille** [comment]
@jamesward can this be reopened or is a new issue preferred?

**Comment by jamesward** [comment]
See: https://github.com/webjars/webjars/issues/1863

**Comment by alvarezguille** [comment]
Thanks, I'll subscribe to that issue
